<script setup lang="ts">
import { computed, ref } from 'vue'
import { contentActionLabels, getSessionApiKey, makeContentPayload, runContentAi, type ContentAiAction } from '@/lib/ai'
import { isDesktop } from '@/lib/native'
import { downloadText } from '@/lib/code-image'
import { useWorkbenchStore } from '@/stores/workbench'

const store = useWorkbenchStore(); const action = ref<ContentAiAction>('summarize'); const content = ref(''); const profileId = ref(''); const running = ref(false); const result = ref(''); const error = ref('')
const profile = computed(() => store.aiProfiles.find((item) => item.id === profileId.value) ?? store.aiProfiles[0])
const payload = computed(() => makeContentPayload(action.value, content.value))
async function run() { error.value = ''; result.value = ''; if (!content.value.trim()) { error.value = '先粘贴或输入需要处理的内容。'; return }; const selected = profile.value; if (!selected) { error.value = '先到设置中配置一个 OpenAI 兼容服务。'; return }; const key = getSessionApiKey(selected.id); if (!isDesktop() && !key) { error.value = '浏览器开发模式需要在设置页重新输入 Session API Key；桌面版从系统凭据库读取。'; return } const job = store.addJob('ai', contentActionLabels[action.value], ['用户粘贴文本']); store.updateJob(job.id, { status: 'running', progress: 12, detail: '正在发送用户确认的文本…' }); running.value = true; try { result.value = await runContentAi(selected, key, action.value, content.value); if (!result.value) throw new Error('服务没有返回文本。'); store.updateJob(job.id, { status: 'succeeded', progress: 100, outputNames: ['AI 草稿'], detail: '结果仅作为草稿，等待用户复制或导出。' }) } catch (reason) { const detail = reason instanceof Error ? reason.message : 'AI 请求失败。'; error.value = detail; store.updateJob(job.id, { status: 'failed', progress: 100, errorCode: 'AI_REQUEST_FAILED', detail }) } finally { running.value = false } }
async function copy() { if (result.value) await navigator.clipboard.writeText(result.value) }
function exportDraft() { if (result.value) downloadText(`toolknit-${action.value}-draft.md`, result.value, 'text/markdown;charset=utf-8') }
</script>

<template>
  <div class="ai-studio page-enter"><section class="page-heading"><div><p class="eyebrow">BYO AI CONTENT STUDIO</p><h2>把文本交给 AI 前，<em>先看清它会收到什么。</em></h2><p>只发送你在左侧明确输入的文本。结果是草稿，不会自动覆盖文件或写入资料库。</p></div></section><section class="ai-studio-grid"><aside class="ai-action-panel"><p class="eyebrow">01 · ACTION</p><button v-for="label, key in contentActionLabels" :key="key" :class="{ active: action === key }" @click="action = key as ContentAiAction"><b>{{ label }}</b><span>{{ key === 'summarize' ? '将长内容压缩为重点' : key === 'translate' ? '保留结构与原意' : key === 'rewrite' ? '清晰、专业地表达' : key === 'extract' ? '转成可操作的信息' : '从材料生成专业邮件' }}</span></button><label>使用配置<select v-model="profileId"><option value="">{{ profile?.label || '未配置' }}</option><option v-for="item in store.aiProfiles" :key="item.id" :value="item.id">{{ item.label }} · {{ item.model }}</option></select></label><RouterLink to="/settings">管理 API 配置 →</RouterLink></aside><main class="ai-input-panel"><header><p class="eyebrow">02 · CONFIRMED CONTENT</p><span>{{ content.length }} 字符</span></header><textarea v-model="content" placeholder="粘贴会议记录、邮件草稿、网页文字、需求描述或任何你想处理的文本…"></textarea><details><summary>查看本次 API 发送载荷</summary><pre>{{ JSON.stringify(payload, null, 2) }}</pre></details><button class="run-tool" :disabled="running" @click="run">{{ running ? '正在生成草稿…' : contentActionLabels[action] }}</button><p v-if="error" class="ai-error">{{ error }}</p></main><aside class="ai-output-panel"><header><p class="eyebrow">03 · DRAFT RESULT</p><span>需人工确认</span></header><div v-if="result" class="ai-result-text">{{ result }}</div><div v-else class="empty-state">结果会出现在这里。它不会自动保存、发送或覆盖任何文件。</div><footer v-if="result"><button class="quiet-button" @click="copy">复制</button><button class="new-task" @click="exportDraft">导出 Markdown</button></footer></aside></section></div>
</template>
