<script setup lang="ts">
import { computed, ref } from 'vue'
import { useWorkbenchStore } from '@/stores/workbench'
import { useUiStore } from '@/stores/ui'
import { cleanupClipboardAssets, copyClipboardItem, localAssetUrl, setClipboardMonitor } from '@/lib/native'
import { readClipboardPayload } from '@/lib/clipboard'
import AppBreadcrumbs from '@/components/AppBreadcrumbs.vue'
import EmptyState from '@/components/EmptyState.vue'
import { looksLikeCode } from '@/lib/workbench-utils'
const store = useWorkbenchStore(); const ui = useUiStore(); const query = ref(''); const filter = ref('all'); const capturing = ref(false)
const items = computed(() => store.clipboardItems.filter((item) => (filter.value === 'all' || item.kind === filter.value) && `${item.content ?? ''} ${item.preview ?? ''}`.toLowerCase().includes(query.value.toLowerCase())))
async function capture() { capturing.value = true; try { const payload = await readClipboardPayload(); if (!payload) throw new Error('剪贴板中没有支持的文本或图片。'); const kind = payload.kind === 'image' ? 'image' : looksLikeCode(payload.content || '') ? 'code' : 'text'; await store.addClipboardItem({ kind, content: payload.content, preview: payload.preview, assetPath: payload.assetPath, hash: payload.hash }); ui.toast('已保存到剪贴板历史', '内容只保存在这台设备。', 'success') } catch (error) { ui.toast('读取失败', error instanceof Error ? error.message : '无法读取剪贴板。', 'error') } finally { capturing.value = false } }
async function copy(id: string) { const item = store.clipboardItems.find((entry) => entry.id === id); if (!item) return; try { await copyClipboardItem(item); ui.toast('已重新复制', item.kind === 'image' ? '图片已写入系统剪贴板。' : item.content?.slice(0,60), 'success') } catch (error) { ui.toast('复制失败', error instanceof Error ? error.message : '系统拒绝了剪贴板访问。', 'error') } }
async function toggleMonitor() { store.updateSettings({ clipboardEnabled: !store.settings.clipboardEnabled, clipboardPaused: false }); await setClipboardMonitor(store.settings.clipboardEnabled, false); ui.toast(store.settings.clipboardEnabled ? '后台监听已开启' : '后台监听已关闭', '剪贴板内容不会上传。', 'info') }
async function syncAssets(){await cleanupClipboardAssets(store.clipboardItems.map(item=>item.assetPath).filter(Boolean) as string[])}
async function remove(id:string){store.removeClipboardItem(id);await syncAssets()}
async function clear() { if (await ui.confirm({ title:'清空剪贴板历史？', message:'固定项目会保留，其他本地记录将被删除。', danger:true, confirmLabel:'清空' })) {store.clearClipboard();await syncAssets()} }
const formatTime = (value:string) => new Date(value).toLocaleString('zh-CN',{month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit'})
</script>
<template><div class="clipboard-view page-enter"><AppBreadcrumbs :items="[{label:'工作',to:'/'},{label:'剪贴板'}]"/><section class="page-heading clipboard-heading"><div><p class="eyebrow">PRIVATE CLIPBOARD</p><h2>复制过的灵感，<em>不再一闪而过。</em></h2><p>文本、代码和图片仅保存在本机。开启监听前，ToolKnit 不会后台读取剪贴板。</p></div><div class="heading-actions"><button class="quiet-button" @click="capture">{{ capturing?'读取中…':'读取当前内容' }}</button><button class="primary-button" @click="toggleMonitor">{{ store.settings.clipboardEnabled?'关闭监听':'开启后台监听' }}</button></div></section>
<section class="clipboard-warning" :class="{active:store.settings.clipboardEnabled}"><i></i><span><b>{{ store.settings.clipboardEnabled ? (store.settings.clipboardPaused?'监听已暂停':'正在本地监听') : '后台监听未开启' }}</b><small>{{ store.settings.clipboardEnabled?'不做密码过滤；请避免复制不希望保留的敏感内容。':'可随时手动读取当前剪贴板。' }}</small></span><button v-if="store.settings.clipboardEnabled" @click="store.updateSettings({clipboardPaused:!store.settings.clipboardPaused});setClipboardMonitor(true,store.settings.clipboardPaused)">{{ store.settings.clipboardPaused?'继续':'暂停' }}</button></section>
<section class="clipboard-toolbar panel"><input v-model="query" class="search-input" placeholder="搜索剪贴板内容…"/><div><button v-for="option in [['all','全部'],['text','文本'],['code','代码'],['image','图片']]" :key="option[0]" :class="{active:filter===option[0]}" @click="filter=option[0]">{{ option[1] }}</button></div><button class="quiet-button" :disabled="!store.clipboardItems.length" @click="clear">清空</button></section>
<section v-if="items.length" class="clipboard-grid"><article v-for="item in items" :key="item.id" class="clipboard-card panel"><header><span :class="item.kind">{{ item.kind==='image'?'图片':item.kind==='code'?'代码':'文本' }}</span><time>{{ formatTime(item.capturedAt) }}</time><button :class="{pinned:item.pinned}" :title="item.pinned?'取消固定':'固定'" @click="store.toggleClipboardPin(item.id)">⌁</button></header><img v-if="item.kind==='image' && item.assetPath" :src="localAssetUrl(item.assetPath)" alt="剪贴板图片预览"/><pre v-else>{{ item.content }}</pre><footer><button class="primary-button" @click="copy(item.id)">重新复制</button><button class="quiet-button danger" @click="remove(item.id)">删除</button></footer></article></section><EmptyState v-else icon="file-text" title="剪贴板历史还是空的" description="复制一段文字、代码或图片，然后读取当前内容；也可以显式开启后台监听。" action="读取当前剪贴板" @action="capture"/>
</div></template>
