<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import { useRouter } from 'vue-router'
import { readClipboardPayload } from '@/lib/clipboard'
import { getDirectorySize, revealDesktopFile } from '@/lib/native'
import { useWorkbenchStore } from '@/stores/workbench'
import { useUiStore } from '@/stores/ui'
import { toolCatalog } from '@/lib/tool-catalog'
import AppIcon from '@/components/AppIcon.vue'
import EmptyState from '@/components/EmptyState.vue'
const router=useRouter(), store=useWorkbenchStore(), ui=useUiStore(); const pasting=ref(false); const storageSize=ref(0); const dragging=ref(''); const contextTool=ref('')
const catalogMap=new Map(toolCatalog.map(item=>[item.id,item]))
const favorites=computed(()=>store.favorites.slice().sort((a,b)=>a.order-b.order).map(item=>({...item,tool:catalogMap.get(item.toolId)})).filter(item=>item.tool))
const suggested=computed(()=>toolCatalog.filter(item=>item.popular&&!store.favorites.some(f=>f.toolId===item.id)).slice(0,4))
const recentTools=computed(()=>store.toolUsages.map(item=>({usage:item,tool:catalogMap.get(item.toolId)})).filter(item=>item.tool).slice(0,5))
const recentJobs=computed(()=>store.jobs.slice(0,5)); const recentSources=computed(()=>store.sources.slice().sort((a,b)=>(b.lastOpenedAt||b.importedAt).localeCompare(a.lastOpenedAt||a.importedAt)).slice(0,4)); const recentOutputs=computed(()=>store.jobs.filter(j=>j.status==='succeeded'&&(j.outputs?.length||j.outputNames?.length)).slice(0,4))
const studyPercent=computed(()=>store.documents.length?Math.min(100,Math.round((store.documents.filter(d=>d.review?.lastReviewedAt).length/store.documents.length)*100)):0)
const quickActions=[['note','book','新建笔记','/documents?kind=note&create=note'],['question','review','新建错题','/documents?kind=question&create=question'],['annotate','palette','图片标注','/visual'],['code','terminal','代码截图','/code-image'],['pdf','file-pdf','PDF 处理','/tools?group=pdf&operation=merge'],['summary','sparkle','AI 总结','/ai?action=summary']]
function openQuick(id:string,to:string){ if(id==='note'){const doc=store.createNote();router.push({path:'/documents',query:{kind:'note',document:doc.id}})}else if(id==='question'){const doc=store.createQuestion();router.push({path:'/documents',query:{kind:'question',document:doc.id}})}else router.push(to) }
function addFavorite(id:string){store.toggleFavorite(id);ui.toast('已加入常用工具','可用 Ctrl + Alt + 数字快速打开。','success')}
function dropFavorite(target:string){if(!dragging.value||dragging.value===target)return;const ids=favorites.value.map(i=>i.toolId);const from=ids.indexOf(dragging.value),to=ids.indexOf(target);ids.splice(to,0,ids.splice(from,1)[0]);store.reorderFavorites(ids);dragging.value=''}
function moveFavorite(toolId:string,direction:-1|1){const ids=favorites.value.map(item=>item.toolId);const from=ids.indexOf(toolId),to=from+direction;if(from<0||to<0||to>=ids.length)return;[ids[from],ids[to]]=[ids[to],ids[from]];store.reorderFavorites(ids);ui.toast('常用工具顺序已调整',`“${catalogMap.get(toolId)?.title??'工具'}”已移动到快捷位 ${to+1}。`,'success')}
function handleFavoriteKey(event:KeyboardEvent,toolId:string){if(!event.altKey||!['ArrowLeft','ArrowRight'].includes(event.key))return;event.preventDefault();moveFavorite(toolId,event.key==='ArrowLeft'?-1:1)}
async function paste(){pasting.value=true;try{const payload=await readClipboardPayload();if(!payload)throw new Error('剪贴板中没有支持的内容。');await store.addSource({name:payload.name,kind:payload.kind,mime:payload.kind==='image'?'image/png':'text/plain',size:(payload.content??payload.preview??'').length,content:payload.content,preview:payload.preview});ui.toast('已收进资料库',payload.name,'success');router.push('/library')}catch(e){ui.toast('无法读取剪贴板',e instanceof Error?e.message:'读取失败','warning')}finally{pasting.value=false}}
async function openOutput(path?:string){if(path)await revealDesktopFile(path);else router.push('/history')}
const formatTime=(v:string)=>new Date(v).toLocaleString('zh-CN',{month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit'}); const formatBytes=(v:number)=>v<1024?'0 KB':v<1048576?`${(v/1024).toFixed(0)} KB`:`${(v/1048576).toFixed(1)} MB`
onMounted(async()=>{if(store.settings.outputDirectory)storageSize.value=await getDirectorySize(store.settings.outputDirectory)})
</script>
<template><div class="dashboard workbench-dashboard page-enter" @click="contextTool=''">
  <section class="workbench-hero"><div class="hero-copy"><p class="eyebrow">LOCAL DESKTOP WORKBENCH · READY</p><h2>今天想把什么，<em>快速处理掉？</em></h2><p>文件、资料、代码和学习任务都留在本机；从一个动作开始，不必先寻找模块。</p><div class="hero-actions"><RouterLink class="new-task" to="/tools"><AppIcon name="plus" :size="15"/>开始处理文件</RouterLink><button class="secondary-action" :disabled="pasting" @click="paste">{{pasting?'读取中…':'从剪贴板开始'}}</button></div></div><div class="hero-signal"><span>TOOLKNIT / LOCAL</span><b>{{store.jobs.filter(j=>j.status==='running').length.toString().padStart(2,'0')}}</b><small>ACTIVE TASKS</small><i></i></div></section>
  <section class="quick-launch"><header><div><p class="eyebrow">QUICK CREATE</p><h3>直接开始</h3></div><kbd>Ctrl K 搜索全部</kbd></header><div><button v-for="action in quickActions" :key="action[0]" @click="openQuick(action[0],action[3])"><b><AppIcon :name="action[1]" :size="18"/></b><span>{{action[2]}}</span><i>↗</i></button></div></section>
    <section class="dashboard-module favorites-module"><header><div><p class="eyebrow">PINNED INSTRUMENTS</p><h3>我的常用工具</h3></div><small>拖动排序 · Alt + ←/→ 键盘排序 · Ctrl Alt 1–9</small></header><div v-if="favorites.length" class="favorite-grid"><RouterLink v-for="item in favorites" :key="item.toolId" :to="item.tool!.to" class="favorite-card" draggable="true" :title="`Alt + ←/→ 调整顺序；${item.shortcut || '收藏快捷键'} 打开`" @keydown="handleFavoriteKey($event,item.toolId)" @dragstart="dragging=item.toolId" @dragover.prevent @drop.prevent="dropFavorite(item.toolId)" @contextmenu.prevent.stop="contextTool=item.toolId"><span><b><AppIcon :name="item.tool!.icon" :size="18"/></b><kbd v-if="item.shortcut">{{item.shortcut}}</kbd></span><h4>{{item.tool!.title}}</h4><p>{{item.tool!.description}}</p><i>打开 →</i><menu v-if="contextTool===item.toolId"><button @click.prevent="store.toggleFavorite(item.toolId)">取消收藏</button><button @click.prevent="router.push(item.tool!.to)">立即打开</button></menu></RouterLink></div><div v-else class="favorite-empty"><span>还没有固定工具</span><div><button v-for="tool in suggested" :key="tool.id" @click="addFavorite(tool.id)"><AppIcon :name="tool.icon" :size="14"/>＋ {{tool.title}}</button></div></div></section>
  <div class="dashboard-board"><section class="dashboard-module recent-task-module"><header><div><p class="eyebrow">RECENT RUNS</p><h3>最近任务</h3></div><RouterLink to="/history">全部历史 →</RouterLink></header><div v-if="recentJobs.length" class="compact-task-list"><article v-for="job in recentJobs" :key="job.id"><span :class="job.status"><i></i>{{job.status==='succeeded'?'完成':job.status==='failed'?'失败':job.status==='running'?`${job.progress}%`:'等待'}}</span><div><h4>{{job.label}}</h4><p>{{job.outputNames?.join('、')||job.detail||job.inputNames?.join('、')}}</p></div><time>{{formatTime(job.createdAt)}}</time></article></div><EmptyState v-else icon="toolbox" title="还没有处理任务" description="完成一次文件处理后，可从这里快速继续。" action="开始处理" @action="router.push('/tools')"/></section>
    <section class="dashboard-module recent-tool-module"><header><div><p class="eyebrow">RECENT TOOLS</p><h3>最近使用</h3></div></header><div v-if="recentTools.length" class="recent-tool-list"><RouterLink v-for="item in recentTools" :key="item.usage.toolId" :to="item.tool!.to"><b><AppIcon :name="item.tool!.icon" :size="15"/></b><span><strong>{{item.tool!.title}}</strong><small>{{formatTime(item.usage.usedAt)}}</small></span><i>→</i></RouterLink></div><div v-else class="mini-empty">使用过的工具会自动留在这里。</div></section>
    <section class="dashboard-module recent-source-module"><header><div><p class="eyebrow">RECENT MATERIALS</p><h3>最近资料</h3></div><RouterLink to="/library">资料库 →</RouterLink></header><div v-if="recentSources.length" class="recent-source-list"><RouterLink v-for="source in recentSources" :key="source.id" :to="{path:'/library',query:{source:source.id}}"><b>{{source.kind.toUpperCase()}}</b><span><strong>{{source.name}}</strong><small>{{formatBytes(source.size)}} · {{source.tags.join(' / ')||'未分类'}}</small></span></RouterLink></div><div v-else class="mini-empty">拖入 PDF、图片或代码建立你的本地资料库。</div></section>
    <section class="dashboard-module study-module"><header><div><p class="eyebrow">LEARNING PULSE</p><h3>学习进度</h3></div><RouterLink to="/review">开始复习 →</RouterLink></header><div class="study-gauge" :style="{'--progress':`${studyPercent}%`}"><b>{{studyPercent}}<small>%</small></b><span>已复习覆盖</span></div><div class="study-stats"><span><b>{{store.dueDocuments.length}}</b>今日待复习</span><span><b>{{store.questionCount}}</b>累计错题</span><span><b>{{store.documents.filter(d=>d.kind==='note').length}}</b>学习笔记</span></div></section>
    <section class="dashboard-module recent-output-module"><header><div><p class="eyebrow">OUTPUT SHELF</p><h3>最近生成</h3></div><RouterLink to="/history">查看目录 →</RouterLink></header><div v-if="recentOutputs.length" class="output-list"><button v-for="job in recentOutputs" :key="job.id" @click="openOutput(job.outputs?.[0]?.path)"><b><AppIcon :name="job.kind==='image'?'image':job.kind==='code'?'terminal':'file-text'" :size="15"/></b><span><strong>{{job.outputs?.[0]?.name||job.outputNames?.[0]}}</strong><small>{{job.label}}</small></span><i>{{job.outputs?.[0]?.path?'⌖':'→'}}</i></button></div><div v-else class="mini-empty">生成结果会集中出现在这里。</div></section>
  </div>
  <footer class="system-strip"><span><i class="online"></i><b>LOCAL</b> 文件不上传</span><span><AppIcon name="inbox" :size="13"/><b>{{formatBytes(storageSize)}}</b> 输出占用</span><span><AppIcon name="file-text" :size="13"/><b>{{store.clipboardItems.length}}</b> 剪贴板记录</span><span><AppIcon name="review" :size="13"/><b>{{store.settings.lastBackupAt?formatTime(store.settings.lastBackupAt):'未备份'}}</b> 最近备份</span><RouterLink to="/settings">系统状态 →</RouterLink></footer>
</div></template>
