Exit code: 0
Wall time: 0.4 seconds
Output:
Exit code: 0
Wall time: 0.4 seconds
Output:
<script setup lang="ts">
import { computed, ref, watch } from 'vue'
import { useWorkbenchStore } from '@/stores/workbench'
import FileDropZone from '@/components/FileDropZone.vue'
import { chooseOutputDirectory, exportOutput } from '@/lib/output'
import { isDesktop } from '@/lib/native'
import { useUiStore } from '@/stores/ui'

const store = useWorkbenchStore(); const ui=useUiStore(); const imageFiles=ref<File[]>([]); const images = ref<{ name: string; url: string }[]>([]); const layout = ref<'single' | 'pair' | 'grid'>('single'); const title = ref(''); const watermark = ref('ToolKnit'); const background = ref('#172321'); const exporting = ref(false); const message = ref('导入图片，选择布局后生成一张可分享的 PNG。')
type AnnotationKind = 'box' | 'arrow' | 'text'
interface Annotation { id: number; kind: AnnotationKind; x: number; y: number; text: string; color: string }
const annotationTool = ref<AnnotationKind>('box'); const annotationText = ref('重点'); const annotationColor = ref('#ffbf69'); const annotations = ref<Annotation[]>([])
const slots = computed(() => layout.value === 'single' ? 1 : layout.value === 'pair' ? 2 : 4)
watch(imageFiles, selected=>{images.value.forEach(item=>URL.revokeObjectURL(item.url));images.value=selected.slice(0,4).map(file=>({name:file.name,url:URL.createObjectURL(file)}));message.value=images.value.length?`已载入 ${images.value.length} 张图片。`:'请选择图片文件。'})
function placeAnnotation(event: MouseEvent) { if (!images.value.length) return; const target = event.currentTarget as HTMLElement; const rect = target.getBoundingClientRect(); const x = Math.max(.03, Math.min(.92, (event.clientX - rect.left) / rect.width)); const y = Math.max(.06, Math.min(.91, (event.clientY - rect.top) / rect.height)); annotations.value.push({ id: Date.now() + Math.random(), kind: annotationTool.value, x, y, text: annotationText.value.trim() || '重点', color: annotationColor.value }); message.value = '标注已添加到导出预览。' }
function removeAnnotation(id: number) { annotations.value = annotations.value.filter((item) => item.id !== id) }
function drawAnnotation(ctx: CanvasRenderingContext2D, annotation: Annotation, canvasHeight: number) { const x = annotation.x * 1600, y = annotation.y * canvasHeight; ctx.strokeStyle = annotation.color; ctx.fillStyle = annotation.color; ctx.lineWidth = 8; ctx.lineJoin = 'round'; if (annotation.kind === 'box') { ctx.strokeRect(x - 120, y - 78, 240, 156); return } if (annotation.kind === 'arrow') { ctx.beginPath(); ctx.moveTo(x - 145, y + 100); ctx.lineTo(x + 105, y - 70); ctx.stroke(); ctx.beginPath(); ctx.moveTo(x + 105, y - 70); ctx.lineTo(x + 45, y - 62); ctx.lineTo(x + 82, y - 12); ctx.closePath(); ctx.fill(); return } ctx.font = '700 34px "Noto Sans SC", sans-serif'; ctx.fillText(annotation.text.slice(0, 26), x, y) }
function drawCover(ctx: CanvasRenderingContext2D, image: HTMLImageElement, x: number, y: number, width: number, height: number) { const ratio = Math.max(width / image.naturalWidth, height / image.naturalHeight); const drawWidth = image.naturalWidth * ratio; const drawHeight = image.naturalHeight * ratio; ctx.drawImage(image, x + (width - drawWidth) / 2, y + (height - drawHeight) / 2, drawWidth, drawHeight) }
async function exportCard() { if (!images.value.length) { message.value = '先至少导入一张图片。'; return } if(isDesktop()&&!store.settings.outputDirectory){const directory=await chooseOutputDirectory();if(!directory)return;store.updateSettings({outputDirectory:directory})} exporting.value = true; try { const canvas = document.createElement('canvas'); canvas.width = 1600; canvas.height = layout.value === 'single' ? 1100 : 1200; const ctx = canvas.getContext('2d'); if (!ctx) throw new Error('浏览器不支持画布导出。'); ctx.fillStyle = background.value; ctx.fillRect(0, 0, canvas.width, canvas.height); const loaded = await Promise.all(images.value.map((item) => new Promise<HTMLImageElement>((resolve, reject) => { const image = new Image(); image.onload = () => resolve(image); image.onerror = reject; image.src = item.url }))); const pad = 48; const titleHeight = title.value.trim() ? 130 : 50; const areaY = titleHeight; const areaH = canvas.height - titleHeight - 48; if (layout.value === 'single') drawCover(ctx, loaded[0], pad, areaY, canvas.width - pad * 2, areaH); else if (layout.value === 'pair') { const width = (canvas.width - pad * 3) / 2; [0, 1].forEach((index) => loaded[index] && drawCover(ctx, loaded[index], pad + index * (width + pad), areaY, width, areaH)) } else { const width = (canvas.width - pad * 3) / 2, height = (areaH - pad) / 2; [0, 1, 2, 3].forEach((index) => loaded[index] && drawCover(ctx, loaded[index], pad + (index % 2) * (width + pad), areaY + Math.floor(index / 2) * (height + pad), width, height)) } if (title.value.trim()) { ctx.fillStyle = '#f2f6f2'; ctx.font = '600 46px "Noto Sans SC", sans-serif'; ctx.fillText(title.value.trim().slice(0, 42), pad, 73) } annotations.value.forEach((annotation) => drawAnnotation(ctx, annotation, canvas.height)); ctx.fillStyle = '#a7cdb9'; ctx.font = '500 20px ui-monospace, monospace'; ctx.textAlign = 'right'; ctx.fillText(watermark.value || 'ToolKnit', canvas.width - pad, canvas.height - 19); const blob=await new Promise<Blob|null>(resolve=>canvas.toBlob(resolve,'image/png'));if(!blob)throw new Error('无法生成 PNG。');const name=`toolknit-card-${Date.now()}.png`;const output=await exportOutput(store.settings.outputDirectory,name,blob,'image/png'); const job = store.addJob('image', '图片分享卡', images.value.map((item) => item.name),{toolId:'visual-card',route:'/visual',inputs:imageFiles.value.map(f=>({name:f.name,size:f.size,mime:f.type,path:(f as File&{path?:string}).path})),parameters:{layout:layout.value,title:title.value,watermark:watermark.value,background:background.value},retryable:true}); store.updateJob(job.id, { status: 'succeeded', progress: 100, outputNames: [name], outputs:[output], detail: '已导出新的 PNG 分享卡。' }); message.value = 'PNG 分享卡已导出。';ui.toast('图片分享卡已生成',output.path||name,'success') } catch (error) { message.value = error instanceof Error ? error.message : '导出失败。';ui.toast('导出失败',message.value,'error') } finally { exporting.value = false } }
</script>

<template>
  <div class="visual-studio page-enter"><section class="page-heading"><div><p class="eyebrow">IMAGE EXPRESSION STUDIO</p><h2>把几张图片，<em>组织成一句完整表达。</em></h2><p>本工具只使用你主动导入的图片，在本地画布中合成并导出新的 PNG。</p></div></section><section class="visual-grid"><aside class="visual-controls"><p class="eyebrow">01 · CONTENT</p><FileDropZone v-model="imageFiles" accept="image/*" title="拖入图片" hint="最多使用前 4 张图片" @error="message=$event"/><p class="eyebrow">02 · LAYOUT</p><div class="layout-options"><button :class="{ active: layout === 'single' }" @click="layout = 'single'">单图</button><button :class="{ active: layout === 'pair' }" @click="layout = 'pair'">双图</button><button :class="{ active: layout === 'grid' }" @click="layout = 'grid'">四宫格</button></div><label>标题<input v-model="title" placeholder="可选，例如：本周记录" /></label><label>水印<input v-model="watermark" /></label><label>背景色<input v-model="background" type="color" /></label><div class="annotation-controls"><p class="eyebrow">03 · ANNOTATE</p><div class="layout-options"><button :class="{ active: annotationTool === 'box' }" @click="annotationTool = 'box'">方框</button><button :class="{ active: annotationTool === 'arrow' }" @click="annotationTool = 'arrow'">箭头</button><button :class="{ active: annotationTool === 'text' }" @click="annotationTool = 'text'">文字</button></div><label>标注文字<input v-model="annotationText" /></label><label>标注颜色<input v-model="annotationColor" type="color" /></label><p class="annotation-hint">选择样式后，直接点右侧预览放置标注。</p></div></aside><main class="visual-preview"><header><p class="eyebrow">03 · EXPORT PREVIEW</p><span>{{ images.length }}/{{ slots }} 图片</span></header><div class="card-preview annotation-canvas" :style="{ background }" @click="placeAnnotation"><h3 v-if="title">{{ title }}</h3><div class="preview-images" :class="layout"><img v-for="item in images.slice(0, slots)" :key="item.url" :src="item.url" :alt="item.name" /><span v-if="!images.length">预览区域</span></div><button v-for="annotation in annotations" :key="annotation.id" class="annotation-mark" :class="annotation.kind" :style="{ left: `${annotation.x * 100}%`, top: `${annotation.y * 100}%`, color: annotation.color, borderColor: annotation.color }" title="点击删除标注" @click.stop="removeAnnotation(annotation.id)">{{ annotation.kind === 'arrow' ? '↗' : annotation.kind === 'text' ? annotation.text : '' }}</button><small>{{ watermark || 'ToolKnit' }}</small></div><footer><p>{{ message }}</p><button class="run-tool" :disabled="exporting" @click="exportCard">{{ exporting ? '正在导出…' : '导出 PNG 分享卡' }}</button></footer></main></section></div>
</template>
