<script setup lang="ts">
import { computed, ref } from 'vue'
import { useWorkbenchStore } from '@/stores/workbench'

const store = useWorkbenchStore(); const input = ref<HTMLInputElement>(); const images = ref<{ name: string; url: string }[]>([]); const layout = ref<'single' | 'pair' | 'grid'>('single'); const title = ref(''); const watermark = ref('ToolKnit'); const background = ref('#172321'); const exporting = ref(false); const message = ref('导入图片，选择布局后生成一张可分享的 PNG。')
const slots = computed(() => layout.value === 'single' ? 1 : layout.value === 'pair' ? 2 : 4)
function choose(event: Event) { const selected = Array.from((event.target as HTMLInputElement).files ?? []).filter((file) => file.type.startsWith('image/')); images.value.forEach((item) => URL.revokeObjectURL(item.url)); images.value = selected.slice(0, 4).map((file) => ({ name: file.name, url: URL.createObjectURL(file) })); message.value = images.value.length ? `已载入 ${images.value.length} 张图片。` : '请选择图片文件。' }
function drawCover(ctx: CanvasRenderingContext2D, image: HTMLImageElement, x: number, y: number, width: number, height: number) { const ratio = Math.max(width / image.naturalWidth, height / image.naturalHeight); const drawWidth = image.naturalWidth * ratio; const drawHeight = image.naturalHeight * ratio; ctx.drawImage(image, x + (width - drawWidth) / 2, y + (height - drawHeight) / 2, drawWidth, drawHeight) }
async function exportCard() { if (!images.value.length) { message.value = '先至少导入一张图片。'; return } exporting.value = true; try { const canvas = document.createElement('canvas'); canvas.width = 1600; canvas.height = layout.value === 'single' ? 1100 : 1200; const ctx = canvas.getContext('2d'); if (!ctx) throw new Error('浏览器不支持画布导出。'); ctx.fillStyle = background.value; ctx.fillRect(0, 0, canvas.width, canvas.height); const loaded = await Promise.all(images.value.map((item) => new Promise<HTMLImageElement>((resolve, reject) => { const image = new Image(); image.onload = () => resolve(image); image.onerror = reject; image.src = item.url }))); const pad = 48; const titleHeight = title.value.trim() ? 130 : 50; const areaY = titleHeight; const areaH = canvas.height - titleHeight - 48; if (layout.value === 'single') drawCover(ctx, loaded[0], pad, areaY, canvas.width - pad * 2, areaH); else if (layout.value === 'pair') { const width = (canvas.width - pad * 3) / 2; [0, 1].forEach((index) => loaded[index] && drawCover(ctx, loaded[index], pad + index * (width + pad), areaY, width, areaH)) } else { const width = (canvas.width - pad * 3) / 2, height = (areaH - pad) / 2; [0, 1, 2, 3].forEach((index) => loaded[index] && drawCover(ctx, loaded[index], pad + (index % 2) * (width + pad), areaY + Math.floor(index / 2) * (height + pad), width, height)) } if (title.value.trim()) { ctx.fillStyle = '#f2f6f2'; ctx.font = '600 46px "Noto Sans SC", sans-serif'; ctx.fillText(title.value.trim().slice(0, 42), pad, 73) } ctx.fillStyle = '#a7cdb9'; ctx.font = '500 20px ui-monospace, monospace'; ctx.textAlign = 'right'; ctx.fillText(watermark.value || 'ToolKnit', canvas.width - pad, canvas.height - 19); const url = canvas.toDataURL('image/png'); const link = document.createElement('a'); link.href = url; link.download = `toolknit-card-${Date.now()}.png`; link.click(); const job = store.addJob('image', '图片分享卡', images.value.map((item) => item.name)); store.updateJob(job.id, { status: 'succeeded', progress: 100, outputNames: [link.download], detail: '已导出新的 PNG 分享卡。' }); message.value = 'PNG 分享卡已导出。' } catch (error) { message.value = error instanceof Error ? error.message : '导出失败。' } finally { exporting.value = false } }
</script>

<template>
  <div class="visual-studio page-enter"><section class="page-heading"><div><p class="eyebrow">IMAGE EXPRESSION STUDIO</p><h2>把几张图片，<em>组织成一句完整表达。</em></h2><p>本工具只使用你主动导入的图片，在本地画布中合成并导出新的 PNG。</p></div></section><section class="visual-grid"><aside class="visual-controls"><p class="eyebrow">01 · CONTENT</p><button class="select-files" @click="input?.click()">导入图片</button><input ref="input" class="visually-hidden" type="file" accept="image/*" multiple @change="choose" /><div class="visual-thumbs"><img v-for="item in images" :key="item.url" :src="item.url" :alt="item.name" /></div><p class="eyebrow">02 · LAYOUT</p><div class="layout-options"><button :class="{ active: layout === 'single' }" @click="layout = 'single'">单图</button><button :class="{ active: layout === 'pair' }" @click="layout = 'pair'">双图</button><button :class="{ active: layout === 'grid' }" @click="layout = 'grid'">四宫格</button></div><label>标题<input v-model="title" placeholder="可选，例如：本周记录" /></label><label>水印<input v-model="watermark" /></label><label>背景色<input v-model="background" type="color" /></label></aside><main class="visual-preview"><header><p class="eyebrow">03 · EXPORT PREVIEW</p><span>{{ images.length }}/{{ slots }} 图片</span></header><div class="card-preview" :style="{ background }"><h3 v-if="title">{{ title }}</h3><div class="preview-images" :class="layout"><img v-for="item in images.slice(0, slots)" :key="item.url" :src="item.url" :alt="item.name" /><span v-if="!images.length">预览区域</span></div><small>{{ watermark || 'ToolKnit' }}</small></div><footer><p>{{ message }}</p><button class="run-tool" :disabled="exporting" @click="exportCard">{{ exporting ? '正在导出…' : '导出 PNG 分享卡' }}</button></footer></main></section></div>
</template>
