<script setup lang="ts">
import { computed, onBeforeUnmount, onMounted, ref, watch } from 'vue'
import { inspectDesktopInputFile, isDesktop, listenWindowFileDrops, readDesktopInputFile } from '@/lib/native'
import { acceptsDroppedFile, exceedsDroppedFileLimit, filesWithinDropBudget, formatDropFileSize } from '@/lib/file-drop-policy'
import AppIcon from '@/components/AppIcon.vue'
const props=withDefaults(defineProps<{modelValue:File[];accept?:string;multiple?:boolean;title?:string;hint?:string;disabled?:boolean;maxFileBytes?:number;maxTotalBytes?:number;maxFiles?:number;desktopPathOnly?:boolean}>(),{accept:'*/*',multiple:true,title:'拖入文件立即开始',hint:'支持批量文件；原件保持只读',disabled:false,maxFiles:100,desktopPathOnly:false})
const emit=defineEmits<{ 'update:modelValue':[files:File[]]; 'desktop-paths':[paths:string[]]; 'request-desktop-choose':[]; error:[message:string] }>();const input=ref<HTMLInputElement>();const active=ref(false);const loading=ref(false);const previews=ref(new Map<File,string>());let unlisten:()=>void=()=>{};let disposed=false
const files=computed(()=>props.modelValue)
function accepted(file:Pick<File,'name'|'type'>){return acceptsDroppedFile(file,props.accept)}
function update(next:File[]){if(props.disabled)return;const compatible=next.filter(accepted);const perFileValid=compatible.filter(file=>!exceedsDroppedFileLimit(file,props.maxFileBytes));const budgeted=filesWithinDropBudget(perFileValid,props.maxTotalBytes);if(compatible.length!==next.length)emit('error',`${next.length-compatible.length} 个文件类型不受当前工具支持。`);if(perFileValid.length!==compatible.length)emit('error',`${compatible.length-perFileValid.length} 个文件超过 ${formatDropFileSize(props.maxFileBytes||0)}，未载入内存。`);if(budgeted.rejected)emit('error',`${budgeted.rejected} 个文件会使本次输入超过 ${formatDropFileSize(props.maxTotalBytes||0)}，未载入内存。`);const limit=props.multiple?Math.max(1,Math.trunc(props.maxFiles)):1;if(budgeted.files.length>limit)emit('error',`一次最多选择 ${limit} 个文件，其余文件未载入。`);emit('update:modelValue',budgeted.files.slice(0,limit))}
function receive(list:FileList|File[]){if(!props.disabled)update(Array.from(list))}function dragEnter(){if(!props.disabled)active.value=true}function choose(event:Event){const target=event.target as HTMLInputElement;if(!props.disabled)receive(target.files||[]);target.value=''}function drop(event:DragEvent){active.value=false;if(props.desktopPathOnly&&isDesktop())return;if(!props.disabled&&event.dataTransfer?.files.length)receive(event.dataTransfer.files)}function remove(index:number){if(!props.disabled)update(files.value.filter((_,i)=>i!==index))}function clear(){if(!props.disabled)update([]);if(input.value)input.value.value=''}
function preview(file:File){if(!file.type.startsWith('image/'))return '';if(!previews.value.has(file))previews.value.set(file,URL.createObjectURL(file));return previews.value.get(file)!}
function chooseFiles(){if(props.desktopPathOnly&&isDesktop()){emit('request-desktop-choose');return}input.value?.click()}
const formatSize=formatDropFileSize
watch(files,current=>{for(const[file,url]of previews.value)if(!current.includes(file)){URL.revokeObjectURL(url);previews.value.delete(file)}})
onMounted(async()=>{try{const stop=await listenWindowFileDrops(async paths=>{if(props.disabled)return;loading.value=true;try{const loaded:File[]=[];const acceptedPaths:string[]=[];const acceptedMetadata:{path:string;size:number}[]=[];const limit=props.multiple?Math.max(1,Math.trunc(props.maxFiles)):1;if(paths.length>limit)emit('error',`一次最多选择 ${limit} 个文件，其余文件未载入。`);for(const path of paths.slice(0,limit)){if(props.disabled)break;const metadata=await inspectDesktopInputFile(path);const candidate={name:metadata.name,type:metadata.mime,size:metadata.size};if(!accepted(candidate)){emit('error',`“${metadata.name}”的文件类型不受当前工具支持，未载入内存。`);continue}if(exceedsDroppedFileLimit(candidate,props.maxFileBytes)){emit('error',`“${metadata.name}”超过 ${formatDropFileSize(props.maxFileBytes||0)}，未载入内存。`);continue}acceptedPaths.push(path);acceptedMetadata.push({path,size:metadata.size})}const budgeted=filesWithinDropBudget(acceptedMetadata,props.maxTotalBytes);if(budgeted.rejected)emit('error',`${budgeted.rejected} 个文件会使本次输入超过 ${formatDropFileSize(props.maxTotalBytes||0)}，未载入内存。`);const budgetPaths=new Set(budgeted.files.map(item=>item.path));if(props.desktopPathOnly){emit('desktop-paths',acceptedPaths.filter(path=>budgetPaths.has(path)));return}for(const path of acceptedPaths)if(budgetPaths.has(path))loaded.push(await readDesktopInputFile(path));update(loaded)}catch(error){emit('error',error instanceof Error?error.message:'无法读取拖入的文件。')}finally{loading.value=false}});if(disposed)stop();else unlisten=stop}catch(error){if(!disposed)emit('error',error instanceof Error?error.message:'无法启用桌面拖放。')}})
onBeforeUnmount(()=>{disposed=true;unlisten();previews.value.forEach(URL.revokeObjectURL)})
</script>
<template><section class="unified-drop" :class="{active:active&&!disabled,filled:files.length,disabled}" :aria-busy="loading" :aria-disabled="disabled" @dragenter.prevent="dragEnter" @dragover.prevent @dragleave.prevent="active=false" @drop.prevent="drop"><div class="drop-intro"><b><AppIcon name="inbox" :size="22"/></b><span><strong>{{loading?(desktopPathOnly?'正在建立本地索引…':'正在读取文件…'):title}}</strong><small>{{disabled?'任务进行中，输入已锁定。':hint}}</small></span><button class="select-files" :disabled="disabled||loading" @click="chooseFiles">选择文件</button><input ref="input" class="visually-hidden" type="file" :multiple="multiple" :accept="accept" :disabled="disabled" @change="choose"/></div><ul v-if="files.length" class="drop-file-list"><li v-for="(file,index) in files" :key="`${file.name}-${file.lastModified}-${index}`"><img v-if="preview(file)" :src="preview(file)" alt=""/><b v-else><AppIcon :name="file.type==='application/pdf'?'file-pdf':file.type.startsWith('text/')?'file-text':'file-code'" :size="16"/></b><span><strong>{{file.name}}</strong><small>{{file.type||'未知类型'}} · {{formatSize(file.size)}}</small></span><button :disabled="disabled" title="移除" @click="remove(index)">×</button></li></ul><button v-if="files.length>1" class="drop-clear" :disabled="disabled" @click="clear">清空全部</button></section></template>
